config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  resources :leads, only: [:create]
  resources :wod_posts, only: [:index, :show], path: '/wod' do
    resources :comments, controller: 'wod_post_comments'
  end
  resources :posts, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :coaches, only: [:index, :show]

  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/wod_post.rb
class WodPost < ActiveRecord::Base
  #include Sluggable
  include FriendlyId

  NEW_WOD_HOUR = 19
  NEW_WOD_DAY = 1

  acts_as_commentable

  validates :title, :content, :effective_date, presence: true
  friendly_id :wod_slug, use: [:slugged, :finders, :history]

  scope :ordered, -> { order("effective_date desc") }
  scope :actual_today, -> { ordered.where("effective_date <= ?", Time.zone.now.beginning_of_day) }
  scope :actual_tomorrow, -> { ordered.where("effective_date <= ?", 1.day.from_now.in_time_zone.beginning_of_day) }
  scope :today, -> { where(effective_date: Time.zone.now.beginning_of_day) }
  scope :tomorrow, -> { where(effective_date: 1.day.from_now.in_time_zone.beginning_of_day) }

  #paginates_per 10

  def to_s
    "#{title}"
  end

  def self.actual_list
    if Time.zone.now.hour >= NEW_WOD_HOUR
      WodPost.actual_tomorrow
    else
      WodPost.actual_today
    end
  end

  def self.actual
    if Time.zone.now.hour >= NEW_WOD_HOUR
      WodPost.tomorrow
    else
      WodPost.today
    end
  end

  def wod_slug
    "#{title}-#{effective_date.strftime('%d-%m-%Y')}"
  end

  def wod_title
    "#{title} #{effective_date.strftime('%d-%m-%Y')}"
  end

  def should_generate_new_friendly_id?
    title_changed? or effective_date_changed? or slug.nil? or slug.blank?
  end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

end

app/controllers/wod_posts_controller.rb
class WodPostsController < ApplicationController
  def index
    posts = WodPost.actual_list
    items = posts.collect{|p| {item: p, comments_count: p.comment_threads.count}}
    render locals: {collection: items}
  end

  def show
    item = WodPost.friendly.find(params[:id])
    comment = Comment.new
    render locals: {item: item, comment: comment}
  end

end

app/helpers/wod_posts_helper.rb
module WodPostsHelper
end

app/views/wod_posts/_disqus.html.slim
#disqus_thread
javascript:
  /**
  * RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  * LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
  */
  /*
  var disqus_config = function () {
  this.page.url = "#{page_url}";
  this.page.identifier = "#{page_identifier}";
  };
  */
  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');

  s.src = '//crossfitredshell.disqus.com/embed.js';

  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();

noscript
  Please enable JavaScript to view the
  a href="https://disqus.com/?ref_noscript" rel="nofollow"
    | comments powered by Disqus.

app/views/wod_posts/_item_block.slim
.row
  .col-md-3
    .wod-list__item-date
      = l item.effective_date, format: :day
  .col-md-6
    / = link_to wod_post_path(item), class: 'text-size-large content-block-sm' do
    / .text-size-large.content-block-sm
    .content-block-sm
      = link_to wod_post_path(item) do
        strong= item.title
    .content-block-sm
      - if short
        = HTML_Truncator.truncate(item.content, 70).html_safe
      - else
        = item.content.html_safe

.row
  .col-md-9.col-md-offset-3
    - if short
      .content-block
        = link_to wod_post_path(item), class: 'btn btn-red--outline' do
          | Посмотреть полностью
          | &nbsp;&rarr;
    - else
      p.content-block-sm
        = render 'wod_posts/share', item: item
      p.content-block-sm
        small
          = link_to wod_post_path(item), class: 'btn btn-sm btn-red--outline' do
            i.fa.fa-comment
            | &nbsp;
            = comments_count

app/views/wod_posts/_share.slim
- share_description = strip_html item.content.html_safe, urlencode_new_line: true
= render 'landing/share',
  locals: {share_title: item.wod_title, share_url: wod_post_url(item),
  share_description: share_description, link_class: 'btn btn-red--outline btn-xs btn-block--line'}

app/views/wod_posts/destroy.html.slim
h1 WodPosts#destroy
p Find me in app/views/wod_posts/destroy.html.slim

app/views/wod_posts/edit.html.slim
h1 WodPosts#edit
p Find me in app/views/wod_posts/edit.html.slim

app/views/wod_posts/index.html.slim
.container
  .content-block
.container
  - collection.each do |collection_item|
    = render 'wod_posts/item_block', item: collection_item[:item], comments_count: collection_item[:comments_count], short: false
    hr.content-block-lg

app/views/wod_posts/show.html.slim
.navbar.navbar-default
  .container
    ul.nav.navbar-nav
      li
        = link_to wod_posts_path do
          | &larr;&nbsp; Все тренировки
.container
  .text-size-larger.content-block-sm
    strong= item.title
  .text-size-large.content-block-sm
    = l item.effective_date, format: :day
  p
    = item.content.html_safe
  hr.content-block
  = render 'wod_posts/share', item: item
  hr.content-block
  //= render 'wod_posts/disqus', page_url: wod_post_url(item), page_identifier: "#{item.class.name.downcase}-#{item.id}"
  .content-block-lg
    .content-block
      .content-block.text-muted.text-size-large
        | Комментарии
      - item.comment_threads.each do |t|
        p
          strong= t.user
          | &nbsp;&nbsp;
          small.text-muted= l t.created_at, format: :created_at
        p
          = t.body
        hr
    - if current_user.present?
      .content-block-lg
        .row
          .col-md-6
            .content-block-sm.text-muted.text-size-large
              | Оставьте комментарий
            = render 'wod_posts/comments/form', item: item, comment: comment
    - else
      .content-block-lg.text-muted
        = link_to t('devise.sessions.new.sign_in'), new_user_session_path
        |  или
        | &nbsp;
        = link_to t('devise.registrations.new.sign_up'), new_user_registration_path
        | , чтобы комментировать

app/views/wod_posts/update.html.slim
h1 WodPosts#update
p Find me in app/views/wod_posts/update.html.slim