config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  resources :leads, only: [:create]
  resources :wod_posts, only: [:index, :show], path: '/wod' do
    resources :comments, controller: 'wod_post_comments'
  end
  resources :posts, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :coaches, only: [:index, :show]

  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  include FriendlyId
  include Sluggable

  validates :title, :content, presence: true
  friendly_id :title, use: [:slugged, :finders, :history]

  scope :active, -> { where("active = ?", true).order('position ASC') }

  mount_uploader :image, CoachUploader

end

app/controllers/coaches_controller.rb
class CoachesController < InheritedResources::Base

  def index
    coaches = Coach.active
    render locals: {collection: coaches}
  end

  def show
    item = Coach.friendly.find(params[:id])
    render locals: {item: item}
  end

  private

    def coach_params
      params.require(:coach).permit(:title, :slug, :content, :active)
    end
end

app/views/coaches/_form.html.slim
= form_for @section do |f|
  - if @section.errors.any?
    #error_explanation
      h2 = "#{pluralize(@section.errors.count, "error")} prohibited this section from being saved:"
      ul
        - @section.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :active
    = f.check_box :active
  .actions = f.submit

app/views/coaches/_item_block.slim
.content-block
  .row
    .col-md-4.text-center
      .content-block-sm
        = link_to coach_path(item) do
          = image_tag item.image.avatar.url, class: 'img-circle center-block content-block welcome-feature-image welcome-feature-image--bordered coach__item-block-avatar'
    .col-md-8
      .content-block-sm.text-size-large
        = link_to coach_path(item) do
          = item.title

      = item.description

hr.content-block

app/views/coaches/edit.html.slim
h1 Editing section

== render 'form'

= link_to 'Show', @section
'|
= link_to 'Back', sections_path

app/views/coaches/index.html.slim
.container
  .content-block-lg
  .content-block-lg
    - collection.each do |item|
      = render 'coaches/item_block', item: item

app/views/coaches/new.html.slim
h1 New section

== render 'form'

= link_to 'Back', sections_path

app/views/coaches/show.html.slim
- content_for :title do
  = page_title item.title
- if item.meta_tags.present?
  - content_for :meta_keywords do
    = item.meta_tags.split(',').join(', ')
- content_for :meta_description do
  = item.meta_description

.navbar.navbar-default
  .container
    ul.nav.navbar-nav
      li
        = link_to coaches_path do
          | &larr;&nbsp; Все тренеры
.container
  .content-block
  .row
    .col-sm-4
      .content-block-sm
        = image_tag item.image.standard.url, class: 'img-circle center-block content-block welcome-feature-image--bordered coach__item-block-avatar'
    .col-sm-7.col-md-offset-1
      .text-size-larger.content-block-sm
        strong= item.title
      .content-block
        = item.content.html_safe
      hr.content-block