config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  resources :leads, only: [:create]
  resources :wod_posts, only: [:index, :show], path: '/wod' do
    resources :comments, controller: 'wod_post_comments'
  end
  resources :posts, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :coaches, only: [:index, :show]

  post '/tinymce_assets' => 'tinymce_assets#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include FriendlyId

  validates :title, :content, :publicated_at, presence: true
  before_validation :set_publicated_at

  friendly_id :title, use: [:slugged, :finders, :history]

  mount_uploader :image, PostUploader

  scope :publicated, -> { where("publicated_at <= ? AND published = ?", "#{Time.zone.now}", true).order("publicated_at desc") }

  def published?
    publicated_at < Time.zone.now
  end

  def active?
    published?
  end

  def to_s
    "#{title}"
  end

  def should_generate_new_friendly_id?
    title_changed? or slug.nil? or slug.blank?
  end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  protected

  def set_announce
    if announce.nil?
      self.announce = content
    end
  end

  private
  def set_publicated_at
    self.publicated_at = Time.zone.now unless publicated_at.present?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    items = Post.publicated
    render locals: {collection: items}
  end

  def show
    item = Post.friendly.find(params[:id])
    render locals: {item: item}
  end

end

app/views/posts/_item_block.slim
.row
  .col-md-3
    .wod-list__item-date
      .wod-list__item-image-block
        = image_tag item.image.standard.url, class: 'wod-list__item-image'
  .col-md-9
    .row
      .col-md-8
        / = link_to post_path(item), class: 'text-size-large content-block-sm' do
        / .text-size-large.content-block-sm
        .content-block-sm
          small.text-muted= l item.publicated_at, format: :day
        .content-block-sm.text-size-large
          = link_to post_path(item) do
            strong= item.title
        .content-block-sm
          - if short
            = HTML_Truncator.truncate(item.content, 70).html_safe
          - else
            = item.content.html_safe

    .content-block-sm
      - if short
        .content-block
          = link_to post_path(item), class: 'btn btn-red--outline' do
            | Читать дальше
            | &nbsp;&rarr;
      - else
        p.content-block-sm
          = render 'posts/share', item: item

app/views/posts/_share.slim
- share_description = strip_html item.content.html_safe, urlencode_new_line: true
= render 'landing/share',
  locals: {share_title: item.to_s, share_url: post_url(item),
  share_description: share_description, link_class: 'btn btn-red--outline btn-xs btn-block--line'}

app/views/posts/index.html.slim
.container
  .content-block
.container
  - collection.each do |collection_item|
    = render 'posts/item_block', item: collection_item, short: false
    hr.content-block-lg

app/views/posts/show.html.slim
- content_for :title do
  = page_title item.title
- if item.meta_tags.present?
  - content_for :meta_keywords do
    = item.meta_tags.split(',').join(', ')
- content_for :meta_description do
  = item.meta_description


.navbar.navbar-default
  .container
    ul.nav.navbar-nav
      li
        = link_to posts_path do
          | &larr;&nbsp; Все новости
.container
  .row
    .col-md-8.col-md-offset-2
      .content-block
        .text-size-larger.content-block-sm
          strong= item.title
        .text-muted
          = l item.publicated_at, format: :day
      hr.content-block
      .content-block
        .wod-list__item-image-block
          = image_tag item.image.large.url, class: 'wod-list__item-image'
      p
        = item.content.html_safe
      hr.content-block
      = render 'posts/share', item: item
      hr.content-block